name: CI | Script Check

on:
  push:
    branches:
      - "**"
      - "!master-ci"
      - "!release"

  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Shellcheck
        uses: azohra/shell-linter@v0.6.0
