name: CI | Verify Bash Installer

on:
  push:
    branches:
      - '**'
      - 'master'
      - '!master-ci'
      - '!release'

  pull_request:
    branches:
      - master

  workflow_dispatch:


jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Bash Installer
        run: |
          sudo /bin/bash installer.sh
          sudo systemd-analyze verify openpod.service

      # - name: Validate JSON
      #   uses: limitusus/json-syntax-check@v1
      #   env:
      #     BASE: '/opt/OpenPod'
      #   with:
      #     pattern: "\\.json$"
