name: End To End Integration

on:
  push:
    branches:
      - '**'
      - 'master'
      - '!master-ci'
      - '!release'

  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: webfactory/ssh-agent@v0.5.4
        with:
            ssh-private-key: ${{ secrets.RECURSION_SPACE_ACCESS_TOKEN}}

      - name: Setup Server
        run: |
          sudo apt-get update -y && sudo apt-get upgrade -y
          sudo apt install software-properties-common -y
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt install python3.10 -y
          sudo mkdir -p /opt
          cd /opt

          git clone --single-branch --branch release git@github.com:RecursionSpace/RecursionREST.git

          sudo apt-get install python3.10-venv -y
          sudo python3.10 -m venv /opt/RecursionREST/env
          source /opt/RecursionREST/env/bin/activate
          /opt/RecursionREST/env/bin/python3.10 -m pip install --upgrade pip

          sudo pip install --no-input -U -r /opt/RecursionREST/requirements.txt

          sudo python /opt/RecursionREST/RecursionREST/manage.py migrate --noinput
