# Performs the task of merging from master to the dev-release branch.
# Pings the server to pull an update once the dev-release branch has been merged.

name: Dev Merge & Deploy
on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:

  merge:
    runs-on: ubuntu-latest
    name: Merge To dev-release
    steps:
    - uses: actions/checkout@master

    - name: Wait on check
      uses: fountainhead/action-wait-for-check@v1.0.0
      id: wait-for-build

      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        checkName: build
        ref: ${{ github.event.pull_request.head.sha || github.sha }}

    - name: Create Pull Request

      if: steps.wait-for-build.outputs.conclusion == 'success'
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "dev-release"
        github_token: ${{ secrets.GITHUB_TOKEN }}


    - name: Merge master -> dev-release

      if: steps.wait-for-build.outputs.conclusion == 'success'
      uses: devmasx/merge-branch@1.4.0
      with:
        type: now
        target_branch: dev-release
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Webhook
      if: steps.wait-for-build.outputs.conclusion == 'success'
      uses: distributhor/workflow-webhook@v1
      env:
        webhook_url: "https://dev.recursion.space/webhooks/github/"
        webhook_secret: "Y0uR5ecr3t"
