name: Verify Bash Installer

on:
  push:
    branches:
      - '**'
      - 'master'
      - '!master-ci'
      - '!release'

  pull_request:
    branches:
      - master

  workflow_dispatch:


jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Bash Installer
        run: |
          sudo /bin/bash installer.sh

      - name: Validate JSON
        uses: anyone-developer/anyone-validate-json@main
        with:
          file-extension: '.json'
          read-path: '/opt/OpenPod'
