name: Verify Bash Installer

on:
  push:
    branches:
      - '**'
      - 'master'
      - '!master-ci'
      - '!release'

  pull_request:
    branches:
      - master

  workflow_dispatch:


jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: limitusus/json-syntax-check@v1
        with:
          pattern: "\\.json$"


      - name: Run Bash Installer
        run: |
          sudo /bin/bash installer.sh
        env:
          BASE: '/opt/OpenPod/'



      # - name: Validate JSON
      #   run: |
      #     sudo /bin/bash validate.sh
